include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_use_of_visible_for_testing_member: ignore
  exclude:
    - build/**
    - android/**
    - windows/**
    - ios/**

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    prefer_initializing_formals: false
    prefer_interpolation_to_compose_strings: false
